language: python
python:
  - "3.8"
install:
  - pip install pytest-cov python-coveralls
  - pip install -r requirements.txt
  - python setup.py install
# command to run tests
script: pytest --cov-report term --cov=flightradar24

after_success:
  coveralls
